### ISSUE TITLE
Handling Binary responses

### ISSUE THREAD

**Issue by Rio517** [spieker/rspec-apib#21]
At SuitePad, we have image endpoints that return image files. The generator actually dumps the binary data into the generated apib file. Perhaps we should just ignore that content and list the filename or something?

**Comment by Rio517** [comment]
After the binary is inserted, it causes character encoding issues. 

```
Failure/Error: file.write(data)

Encoding::UndefinedConversionError:
  "\x89" from ASCII-8BIT to UTF-8
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib/writer.rb:20:in `write'
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib/writer.rb:20:in `block in write_to_file'
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib/writer.rb:19:in `open'
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib/writer.rb:19:in `write_to_file'
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib/writer.rb:13:in `write'
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib.rb:47:in `write'
# /usr/local/bundle/gems/rspec-apib-1.0.0/lib/rspec/apib.rb:34:in `block (2 levels) in start'
```

These can be mitigated by opening the file with `'wb'` instead of just `'w'`.
